alias: AT Master Spill Fix Heat
description: >-
  If Master bedroom damper is slightly open for 30 seconds, and the current
  temperature is below or equal to the target temperature, open the damper wider
  to prevent lounge overheat. This is only enabled at night as during the day it
  doesnt matter.
trigger:
  - platform: numeric_state
    entity_id: fan.damper_master
    for:
      hours: 0
      minutes: 0
      seconds: 30
    attribute: percentage
    below: 21
    above: 1
condition:
  - condition: device
    device_id: airtouch4_device_id
    domain: climate
    entity_id: climate.ac_daikin
    type: is_hvac_mode
    hvac_mode: heat
  - condition: state
    entity_id: fan.damper_master
    state: "on"
  - condition: state
    entity_id: climate.itc_master
    attribute: preset_mode
    state: ITC
  - condition: time
    before: "07:00:00"
    after: "16:00:00"
    enabled: false
  - alias: >-
      Current room temperature is no more than 0.2 degrees above target
      temperature
    condition: template
    value_template: >-
      {{ state_attr("climate.itc_master", "current_temperature") -
      state_attr("climate.itc_master", "temperature") <= 0.2}}
action:
  - service: climate.set_preset_mode
    data:
      preset_mode: Damper
    target:
      entity_id:
        - climate.itc_master
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: fan.set_percentage
    data:
      percentage: 40
    target:
      entity_id: fan.damper_master
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: climate.set_preset_mode
    data:
      preset_mode: ITC
    target:
      entity_id:
        - climate.itc_master
trace:
  stored_traces: 50
mode: single
