alias: Office 0530 weekdays below 11
description: Turn on the office to 22deg at 5.30am weekdays from March to November
trigger:
  - platform: time
    at: "05:30:00"
condition:
  - condition: state
    entity_id: input_boolean.office_automations_enabled
    state: "on"
  - condition: time
    before: "00:00:00"
    weekday:
      - mon
      - tue
      - thu
      - fri
      - wed
    after: "00:00:00"
  - condition: template
    value_template: "{{ now().month in [3, 4, 5, 6, 7, 8, 9, 10] }}"
    alias: Month is Mar - Oct
  - condition: numeric_state
    entity_id: sensor.officesensor_temperature
    below: 11
action:
  - service: climate.set_hvac_mode
    data:
      hvac_mode: heat
    target:
      entity_id: climate.office_daikin
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: climate.set_temperature
    data:
      temperature: 22
    target:
      entity_id: climate.office_daikin
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: climate.set_fan_mode
    data:
      fan_mode: "3"
    target:
      entity_id: climate.office_daikin
mode: single