alias: ATP Guest Overnight Limit Damper Overheat Overcool 2200 - 0630
description: >-
  This automation simply stops the room damper opening past a certian percentage. When a single
  room is heating / cooling at night the Airtouch would completely open the damper and as a result
  the room would get very hot or cold. This was particularly noticable in smaller rooms.
  This automation reduces the maximum heating or cooling to the room.
triggers:
  - trigger: numeric_state
    entity_id:
      - cover.pa_guest_damper
    attribute: current_position
    above: 61
    for:
      hours: 0
      minutes: 0
      seconds: 2
conditions:
  - alias: HVAC is in heating or cooling mode
    condition: or
    conditions:
      - condition: state
        entity_id: climate.pa_daikin
        state: cool
      - condition: state
        entity_id: climate.pa_daikin
        state: heat
  - alias: Room is enabled
    condition: state
    entity_id: cover.pa_guest_damper
    state: open
  - condition: time
    before: "06:30:00"
    after: "21:30:00"
  - alias: Current temperature is at least 0.3 degrees from target
    condition: or
    conditions:
      - alias: Heating mode & no more than 0.2 degrees above the setpoint
        condition: and
        conditions:
          - condition: state
            entity_id: climate.pa_daikin
            state: heat
          - condition: template
            value_template: |-
              {{ state_attr("climate.pa_guest", "current_temperature") -
                    state_attr("climate.pa_guest", "temperature") <= 0.25}}
      - alias: Cooling mode & no more than 0.2 degrees below the setpoint
        condition: and
        conditions:
          - condition: state
            entity_id: climate.pa_daikin
            state: cool
          - condition: template
            value_template: >-
              {{ (state_attr("climate.pa_guest", "temperature") -
              state_attr("climate.pa_guest", "current_temperature") <= 0.25 ) }}
actions:
  - alias: Damper to 60%
    action: cover.set_cover_position
    data:
      position: 60
    target:
      entity_id: cover.pa_guest_damper
  - alias: Reset to temperature control
    action: climate.set_temperature
    data:
      temperature: "{{ state_attr('climate.pa_guest', 'temperature') }}"
    target:
      entity_id:
        - climate.pa_guest
mode: single
