alias: AT Guest Spill Fix Heat
description: >-
  If guest bedroom damper is slightly open for 30 seconds, and the current
  temperature is below or equal to the target temperature, open the damper wider
  to prevent lounge overheat. This is only enabled at night as during the day it
  doesnt matter.
trigger:
  - platform: numeric_state
    entity_id: fan.damper_guest
    for:
      hours: 0
      minutes: 0
      seconds: 30
    attribute: percentage
    below: 21
    above: 1
condition:
  - condition: device
    device_id: airtouch4_device_id
    domain: climate
    entity_id: climate.ac_daikin
    type: is_hvac_mode
    hvac_mode: heat
  - condition: state
    entity_id: fan.damper_guest
    state: "on"
  - condition: state
    entity_id: climate.itc_guest
    attribute: preset_mode
    state: ITC
  - condition: time
    before: "07:00:00"
    after: "13:00:00"
    enabled: false
  - condition: template
    value_template: >-
      {{ state_attr("climate.itc_guest", "current_temperature") -
      state_attr("climate.itc_guest", "temperature") <= 0.2}}
    alias: >-
      Current room temperature is no more than 0.2 degrees above target
      temperature
action:
  - service: climate.set_preset_mode
    data:
      preset_mode: Damper
    target:
      entity_id: fan.damper_guest
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: fan.set_percentage
    data:
      percentage: 40
    target:
      entity_id: fan.damper_guest
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: climate.set_preset_mode
    data:
      preset_mode: ITC
    target:
      entity_id: fan.damper_guest
mode: single
